image: texlive/texlive:latest-full@sha256:66446fb092ef02d6dc31bba079d9bdc83e8a6af00562c6062bb97ae8e91814ea

variables:
  FILE_NAME: "root"

stages:
  - build

pdflatex:
  stage: build
  script:
    - latexmk -synctex=0 -interaction=nonstopmode --shell-escape -pdf -file-line-error $FILE_NAME.tex
  artifacts:
    paths:
      - $FILE_NAME.pdf
    expire_in: 4 weeks
